/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#0b1326",
        "surface-dim": "#0b1326",
        "surface-bright": "#31394d",
        "surface-container-lowest": "#060e20",
        "surface-container-low": "#131b2e",
        "surface-container": "#171f33",
        "surface-container-high": "#222a3d",
        "surface-container-highest": "#2d3449",
        "surface-variant": "#2d3449",
        "on-surface": "#dae2fd",
        "on-surface-variant": "#cfc2d6",
        "inverse-surface": "#dae2fd",
        "inverse-on-surface": "#283044",
        outline: "#988d9f",
        "outline-variant": "#4d4354",
        "surface-tint": "#ddb7ff",
        primary: "#ddb7ff",
        "on-primary": "#490080",
        "primary-container": "#b76dff",
        "on-primary-container": "#400071",
        "inverse-primary": "#842bd2",
        secondary: "#7bd0ff",
        "on-secondary": "#00354a",
        "secondary-container": "#00a6e0",
        "on-secondary-container": "#00374d",
        tertiary: "#bdc2ff",
        "on-tertiary": "#131e8c",
        "tertiary-container": "#7c87f3",
        "on-tertiary-container": "#081486",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#f0dbff",
        "primary-fixed-dim": "#ddb7ff",
        "on-primary-fixed": "#2c0051",
        "on-primary-fixed-variant": "#6900b3",
        "secondary-fixed": "#c4e7ff",
        "secondary-fixed-dim": "#7bd0ff",
        "on-secondary-fixed": "#001e2c",
        "on-secondary-fixed-variant": "#004c69",
        "tertiary-fixed": "#e0e0ff",
        "tertiary-fixed-dim": "#bdc2ff",
        "on-tertiary-fixed": "#000767",
        "on-tertiary-fixed-variant": "#2f3aa3",
        background: "#0b1326",
        "on-background": "#dae2fd",
        "brand-purple": "#a855f7",
        "brand-purple-hover": "#c084fc",
        "brand-purple-deep": "#7e22ce",
        "brand-cyan": "#38bdf8",
        "brand-violet": "#818cf8",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1.5rem",
        margin: "2rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "system-ui", "sans-serif"],
        display: ["'Plus Jakarta Sans'", "sans-serif"],
        headline: ["'Plus Jakarta Sans'", "sans-serif"],
        body: ["'Inter'", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
      },
    },
  },
  plugins: [],
}
